In [1]:
import numpy as np


np.random.seed()

def relu(x):
    return (x > 0) * x

def relu2derive(output):
    return output > 0


alpha = 0.2
hidden_size = 4



streetlights = np.array([[ 1, 0, 1,],
                         [0, 1, 1],
                         [0, 0, 1],
                         [1, 1, 1]
                         ])

# [1 1 0 0]
walk_vs_stop = np.array([1, 1, 0, 0]).T

weights_0_1 =  2*  np.random.random((3, hidden_size)) - 1

print(weights_0_1)



[[-0.73580164 -0.87146858  0.47078902  0.71450152]
 [ 0.8129179   0.74082536  0.04808107 -0.37522193]
 [-0.44712388 -0.69897379 -0.75925813  0.68949256]]
